package com.xti.bank.mapper;

import com.xti.bank.controller.PixTransactionRequest;
import com.xti.bank.domain.PixTransaction;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants.ComponentModel;
import org.mapstruct.ReportingPolicy;

@Mapper(
        componentModel = ComponentModel.SPRING,          // → becomes Spring @Component
        unmappedTargetPolicy = ReportingPolicy.IGNORE,   // don't fail on unmapped fields
        unmappedSourcePolicy = ReportingPolicy.IGNORE
)
public interface PixTransactionMapper {

    @Mapping(target = "id", ignore = true)           // generated by MongoDB
    @Mapping(target = "status", ignore = true)       // we set PENDING manually
    @Mapping(target = "transactionDate", ignore = true) // set in service
    PixTransaction toEntity(PixTransactionRequest request);

    // Optional – if you ever need reverse mapping
    PixTransactionRequest toRequest(PixTransaction entity);
}
